Ext.define('PMDMeta.store.datacite.combobox.LanguageCombo', {
    extend: 'Ext.data.Store',
    model:  'PMDMeta.model.Combobox',
    storeId: 'LanguageCombo',
    data: [
					{abbr:'aa',name:'Afar'},
					{abbr:'ab',name:'Abkhazian'},
					{abbr:'ae',name:'Avestan'},
					{abbr:'af',name:'Afrikaans'},
					{abbr:'ak',name:'Akan'},
					{abbr:'am',name:'Amharic'},
					{abbr:'an',name:'Aragonese'},
					{abbr:'ar',name:'Arabic'},
					{abbr:'as',name:'Assamese'},
					{abbr:'av',name:'Avaric'},
					{abbr:'ay',name:'Aymara'},
					{abbr:'az',name:'Azerbaijani'},
					{abbr:'ba',name:'Bashkir'},
					{abbr:'be',name:'Belarusian'},
					{abbr:'bg',name:'Bulgarian'},
					{abbr:'bh',name:'Bihari languages'},
					{abbr:'bi',name:'Bislama'},
					{abbr:'bm',name:'Bambara'},
					{abbr:'bn',name:'Bengali'},
					{abbr:'bo',name:'Tibetan'},
					{abbr:'br',name:'Breton'},
					{abbr:'bs',name:'Bosnian'},
					{abbr:'ca',name:'Catalan; Valencian'},
					{abbr:'ce',name:'Chechen'},
					{abbr:'ch',name:'Chamorro'},
					{abbr:'co',name:'Corsican'},
					{abbr:'cr',name:'Cree'},
					{abbr:'cs',name:'Czech'},
					{abbr:'cu',name:'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'},
					{abbr:'cv',name:'Chuvash'},
					{abbr:'cy',name:'Welsh'},
					{abbr:'da',name:'Danish'},
					{abbr:'de',name:'German'},
					{abbr:'dv',name:'Divehi; Dhivehi; Maldivian'},
					{abbr:'dz',name:'Dzongkha'},
					{abbr:'ee',name:'Ewe'},
					{abbr:'el',name:'Greek'},
					{abbr:'en',name:'English'},
					{abbr:'eo',name:'Esperanto'},
					{abbr:'es',name:'Spanish; Castilian'},
					{abbr:'et',name:'Estonian'},
					{abbr:'eu',name:'Basque'},
					{abbr:'fa',name:'Persian'},
					{abbr:'ff',name:'Fulah'},
					{abbr:'fi',name:'Finnish'},
					{abbr:'fj',name:'Fijian'},
					{abbr:'fo',name:'Faroese'},
					{abbr:'fr',name:'French'},
					{abbr:'fy',name:'Western Frisian'},
					{abbr:'ga',name:'Irish'},
					{abbr:'gd',name:'Gaelic; Scottish Gaelic'},
					{abbr:'gl',name:'Galician'},
					{abbr:'gn',name:'Guarani'},
					{abbr:'gu',name:'Gujarati'},
					{abbr:'gv',name:'Manx'},
					{abbr:'ha',name:'Hausa'},
					{abbr:'he',name:'Hebrew'},
					{abbr:'hi',name:'Hindi'},
					{abbr:'ho',name:'Hiri Motu'},
					{abbr:'hr',name:'Croatian'},
					{abbr:'ht',name:'Haitian; Haitian Creole'},
					{abbr:'hu',name:'Hungarian'},
					{abbr:'hy',name:'Armenian'},
					{abbr:'hz',name:'Herero'},
					{abbr:'ia',name:'Interlingua (International Auxiliary Language Association)'},
					{abbr:'id',name:'Indonesian'},
					{abbr:'ie',name:'Interlingue; Occidental'},
					{abbr:'ig',name:'Igbo'},
					{abbr:'ii',name:'Sichuan Yi; Nuosu'},
					{abbr:'ik',name:'Inupiaq'},
					{abbr:'io',name:'Ido'},
					{abbr:'is',name:'Icelandic'},
					{abbr:'it',name:'Italian'},
					{abbr:'iu',name:'Inuktitut'},
					{abbr:'ja',name:'Japanese'},
					{abbr:'jv',name:'Javanese'},
					{abbr:'ka',name:'Georgian'},
					{abbr:'kg',name:'Kongo'},
					{abbr:'ki',name:'Kikuyu; Gikuyu'},
					{abbr:'kj',name:'Kuanyama; Kwanyama'},
					{abbr:'kk',name:'Kazakh'},
					{abbr:'kl',name:'Kalaallisut; Greenlandic'},
					{abbr:'km',name:'Central Khmer'},
					{abbr:'kn',name:'Kannada'},
					{abbr:'ko',name:'Korean'},
					{abbr:'kr',name:'Kanuri'},
					{abbr:'ks',name:'Kashmiri'},
					{abbr:'ku',name:'Kurdish'},
					{abbr:'kv',name:'Komi'},
					{abbr:'kw',name:'Cornish'},
					{abbr:'ky',name:'Kirghiz; Kyrgyz'},
					{abbr:'la',name:'Latin'},
					{abbr:'lb',name:'Luxembourgish; Letzeburgesch'},
					{abbr:'lg',name:'Ganda'},
					{abbr:'li',name:'Limburgan; Limburger; Limburgish'},
					{abbr:'ln',name:'Lingala'},
					{abbr:'lo',name:'Lao'},
					{abbr:'lt',name:'Lithuanian'},
					{abbr:'lu',name:'Luba-Katanga'},
					{abbr:'lv',name:'Latvian'},
					{abbr:'mg',name:'Malagasy'},
					{abbr:'mh',name:'Marshallese'},
					{abbr:'mi',name:'Maori'},
					{abbr:'mk',name:'Macedonian'},
					{abbr:'ml',name:'Malayalam'},
					{abbr:'mn',name:'Mongolian'},
					{abbr:'mr',name:'Marathi'},
					{abbr:'ms',name:'Malay'},
					{abbr:'mt',name:'Maltese'},
					{abbr:'my',name:'Burmese'},
					{abbr:'na',name:'Nauru'},
					{abbr:'nb',name:'Bokmål'},
					{abbr:'nd',name:'Ndebele'},
					{abbr:'ne',name:'Nepali'},
					{abbr:'ng',name:'Ndonga'},
					{abbr:'nl',name:'Dutch; Flemish'},
					{abbr:'nn',name:'Norwegian Nynorsk; Nynorsk'},
					{abbr:'no',name:'Norwegian'},
					{abbr:'nr',name:'Ndebele'},
					{abbr:'nv',name:'Navajo; Navaho'},
					{abbr:'ny',name:'Chichewa; Chewa; Nyanja'},
					{abbr:'oc',name:'Occitan (post 1500); Provençal'},
					{abbr:'oj',name:'Ojibwa'},
					{abbr:'om',name:'Oromo'},
					{abbr:'or',name:'Oriya'},
					{abbr:'os',name:'Ossetian; Ossetic'},
					{abbr:'pa',name:'Panjabi; Punjabi'},
					{abbr:'pi',name:'Pali'},
					{abbr:'pl',name:'Polish'},
					{abbr:'ps',name:'Pushto; Pashto'},
					{abbr:'pt',name:'Portuguese'},
					{abbr:'qu',name:'Quechua'},
					{abbr:'rm',name:'Romansh'},
					{abbr:'rn',name:'Rundi'},
					{abbr:'ro',name:'Romanian; Moldavian; Moldovan'},
					{abbr:'ru',name:'Russian'},
					{abbr:'rw',name:'Kinyarwanda'},
					{abbr:'sa',name:'Sanskrit'},
					{abbr:'sc',name:'Sardinian'},
					{abbr:'sd',name:'Sindhi'},
					{abbr:'se',name:'Northern Sami'},
					{abbr:'sg',name:'Sango'},
					{abbr:'si',name:'Sinhala; Sinhalese'},
					{abbr:'sk',name:'Slovak'},
					{abbr:'sl',name:'Slovenian'},
					{abbr:'sm',name:'Samoan'},
					{abbr:'sn',name:'Shona'},
					{abbr:'so',name:'Somali'},
					{abbr:'sq',name:'Albanian'},
					{abbr:'sr',name:'Serbian'},
					{abbr:'ss',name:'Swati'},
					{abbr:'st',name:'Sotho'},
					{abbr:'su',name:'Sundanese'},
					{abbr:'sv',name:'Swedish'},
					{abbr:'sw',name:'Swahili'},
					{abbr:'ta',name:'Tamil'},
					{abbr:'te',name:'Telugu'},
					{abbr:'tg',name:'Tajik'},
					{abbr:'th',name:'Thai'},
					{abbr:'ti',name:'Tigrinya'},
					{abbr:'tk',name:'Turkmen'},
					{abbr:'tl',name:'Tagalog'},
					{abbr:'tn',name:'Tswana'},
					{abbr:'to',name:'Tonga (Tonga Islands)'},
					{abbr:'tr',name:'Turkish'},
					{abbr:'ts',name:'Tsonga'},
					{abbr:'tt',name:'Tatar'},
					{abbr:'tw',name:'Twi'},
					{abbr:'ty',name:'Tahitian'},
					{abbr:'ug',name:'Uighur; Uyghur'},
					{abbr:'uk',name:'Ukrainian'},
					{abbr:'ur',name:'Urdu'},
					{abbr:'uz',name:'Uzbek'},
					{abbr:'ve',name:'Venda'},
					{abbr:'vi',name:'Vietnamese'},
					{abbr:'vo',name:'Volapük'},
					{abbr:'wa',name:'Walloon'},
					{abbr:'wo',name:'Wolof'},
					{abbr:'xh',name:'Xhosa'},
					{abbr:'yi',name:'Yiddish'},
					{abbr:'yo',name:'Yoruba'},
					{abbr:'za',name:'Zhuang; Chuang'},
					{abbr:'zh',name:'Chinese'},
					{abbr:'zu',name:'Zulu'}	
    ]
});
