Ext.define('PMDMeta.store.escidoc.Mimetypes', {
    extend: 'Ext.data.Store',
    model:  'PMDMeta.model.Combobox',
    storeId: 'Mimetypes',
    data: [
        {abbr:'application/activemessage', name:'application/activemessage'},
        {abbr:'application/andrew-inset', name:'application/andrew-inset', ext:'ez'},
        {abbr:'application/annodex', name:'application/annodex', ext:'anx'},
        {abbr:'application/applefile', name:'application/applefile'},
        {abbr:'application/atom+xml', name:'application/atom+xml', ext:'atom'},
        {abbr:'application/atomcat+xml', name:'application/atomcat+xml', ext:'atomcat'},
        {abbr:'application/atomicmail', name:'application/atomicmail'},
        {abbr:'application/atomserv+xml', name:'application/atomserv+xml', ext:'atomsrv'},
        {abbr:'application/batch-SMTP', name:'application/batch-SMTP'},
        {abbr:'application/bbolin', name:'application/bbolin', ext:'lin'},
        {abbr:'application/beep+xml', name:'application/beep+xml'},
        {abbr:'application/cals-1840', name:'application/cals-1840'},
        {abbr:'application/commonground', name:'application/commonground'},
        {abbr:'application/cu-seeme', name:'application/cu-seeme', ext:'cu'},
        {abbr:'application/cybercash', name:'application/cybercash'},
        {abbr:'application/davmount+xml', name:'application/davmount+xml', ext:'davmount'},
        {abbr:'application/dca-rft', name:'application/dca-rft'},
        {abbr:'application/dec-dx', name:'application/dec-dx'},
        {abbr:'application/dicom', name:'application/dicom', ext:'dcm'},
        {abbr:'application/docbook+xml', name:'application/docbook+xml'},
        {abbr:'application/dsptype', name:'application/dsptype', ext:'tsp'},
        {abbr:'application/dvcs', name:'application/dvcs'},
        {abbr:'application/ecmascript', name:'application/ecmascript', ext:'es'},
        {abbr:'application/edi-consent', name:'application/edi-consent'},
        {abbr:'application/edi-x12', name:'application/edi-x12'},
        {abbr:'application/edifact', name:'application/edifact'},
        {abbr:'application/eshop', name:'application/eshop'},
        {abbr:'application/font-sfnt', name:'application/font-sfnt', ext:'otf'},
        {abbr:'application/font-tdpfr', name:'application/font-tdpfr', ext:'pfr'},
        {abbr:'application/font-woff', name:'application/font-woff', ext:'woff'},
        {abbr:'application/futuresplash', name:'application/futuresplash', ext:'spl'},
        {abbr:'application/ghostview', name:'application/ghostview'},
        {abbr:'application/gzip', name:'application/gzip', ext:'gz'},
        {abbr:'application/hta', name:'application/hta', ext:'hta'},
        {abbr:'application/http', name:'application/http'},
        {abbr:'application/hyperstudio', name:'application/hyperstudio'},
        {abbr:'application/iges', name:'application/iges'},
        {abbr:'application/index', name:'application/index'},
        {abbr:'application/index.cmd', name:'application/index.cmd'},
        {abbr:'application/index.obj', name:'application/index.obj'},
        {abbr:'application/index.response', name:'application/index.response'},
        {abbr:'application/index.vnd', name:'application/index.vnd'},
        {abbr:'application/iotp', name:'application/iotp'},
        {abbr:'application/ipp', name:'application/ipp'},
        {abbr:'application/isup', name:'application/isup'},
        {abbr:'application/java-archive', name:'application/java-archive', ext:'jar'},
        {abbr:'application/java-serialized-object', name:'application/java-serialized-object', ext:'ser'},
        {abbr:'application/java-vm', name:'application/java-vm', ext:'class'},
        {abbr:'application/javascript', name:'application/javascript', ext:'js'},
        {abbr:'application/json', name:'application/json', ext:'json'},
        {abbr:'application/m3g', name:'application/m3g', ext:'m3g'},
        {abbr:'application/mac-binhex40', name:'application/mac-binhex40', ext:'hqx'},
        {abbr:'application/mac-compactpro', name:'application/mac-compactpro', ext:'cpt'},
        {abbr:'application/macwriteii', name:'application/macwriteii'},
        {abbr:'application/marc', name:'application/marc'},
        {abbr:'application/mathematica', name:'application/mathematica', ext:'nb'},
        {abbr:'application/mbox', name:'application/mbox', ext:'mbox'},
        {abbr:'application/ms-tnef', name:'application/ms-tnef'},
        {abbr:'application/msaccess', name:'application/msaccess', ext:'mdb'},
        {abbr:'application/msword', name:'application/msword', ext:'doc'},
        {abbr:'application/mxf', name:'application/mxf', ext:'mxf'},
        {abbr:'application/news-message-id', name:'application/news-message-id'},
        {abbr:'application/news-transmission', name:'application/news-transmission'},
        {abbr:'application/ocsp-request', name:'application/ocsp-request'},
        {abbr:'application/ocsp-response', name:'application/ocsp-response'},
        {abbr:'application/octet-stream', name:'application/octet-stream', ext:'bin'},
        {abbr:'application/oda', name:'application/oda', ext:'oda'},
        {abbr:'application/oebps-package+xml', name:'application/oebps-package+xml', ext:'opf'},
        {abbr:'application/ogg', name:'application/ogg', ext:'ogx'},
        {abbr:'application/onenote', name:'application/onenote', ext:'one'},
        {abbr:'application/parityfec', name:'application/parityfec'},
        {abbr:'application/pdf', name:'application/pdf', ext:'pdf'},
        {abbr:'application/pgp-encrypted', name:'application/pgp-encrypted', ext:'pgp'},
        {abbr:'application/pgp-keys', name:'application/pgp-keys', ext:'key'},
        {abbr:'application/pgp-signature', name:'application/pgp-signature', ext:'sig'},
        {abbr:'application/pics-rules', name:'application/pics-rules', ext:'prf'},
        {abbr:'application/pkcs10', name:'application/pkcs10'},
        {abbr:'application/pkcs7-mime', name:'application/pkcs7-mime'},
        {abbr:'application/pkcs7-signature', name:'application/pkcs7-signature'},
        {abbr:'application/pkix-cert', name:'application/pkix-cert'},
        {abbr:'application/pkix-crl', name:'application/pkix-crl'},
        {abbr:'application/pkixcmp', name:'application/pkixcmp'},
        {abbr:'application/postscript', name:'application/postscript', ext:'ps'},
        {abbr:'application/prs.alvestrand.titrax-sheet', name:'application/prs.alvestrand.titrax-sheet'},
        {abbr:'application/prs.cww', name:'application/prs.cww'},
        {abbr:'application/prs.nprend', name:'application/prs.nprend'},
        {abbr:'application/qsig', name:'application/qsig'},
        {abbr:'application/rar', name:'application/rar', ext:'rar'},
        {abbr:'application/rdf+xml', name:'application/rdf+xml', ext:'rdf'},
        {abbr:'application/remote-printing', name:'application/remote-printing'},
        {abbr:'application/riscos', name:'application/riscos'},
        {abbr:'application/rtf', name:'application/rtf', ext:'rtf'},
        {abbr:'application/sdp', name:'application/sdp'},
        {abbr:'application/set-payment', name:'application/set-payment'},
        {abbr:'application/set-payment-initiation', name:'application/set-payment-initiation'},
        {abbr:'application/set-registration', name:'application/set-registration'},
        {abbr:'application/set-registration-initiation', name:'application/set-registration-initiation'},
        {abbr:'application/sgml', name:'application/sgml'},
        {abbr:'application/sgml-open-catalog', name:'application/sgml-open-catalog'},
        {abbr:'application/sieve', name:'application/sieve'},
        {abbr:'application/sla', name:'application/sla', ext:'stl'},
        {abbr:'application/slate', name:'application/slate'},
        {abbr:'application/smil+xml', name:'application/smil+xml', ext:'smi'},
        {abbr:'application/timestamp-query', name:'application/timestamp-query'},
        {abbr:'application/timestamp-reply', name:'application/timestamp-reply'},
        {abbr:'application/vemmi', name:'application/vemmi'},
        {abbr:'application/whoispp-query', name:'application/whoispp-query'},
        {abbr:'application/whoispp-response', name:'application/whoispp-response'},
        {abbr:'application/wita', name:'application/wita'},
        {abbr:'application/x400-bp', name:'application/x400-bp'},
        {abbr:'application/xhtml+xml', name:'application/xhtml+xml', ext:'xhtml'},
        {abbr:'application/xml', name:'application/xml', ext:'xml'},
        {abbr:'application/xml-dtd', name:'application/xml-dtd'},
        {abbr:'application/xml-external-parsed-entity', name:'application/xml-external-parsed-entity'},
        {abbr:'application/xslt+xml', name:'application/xslt+xml', ext:'xsl'},
        {abbr:'application/xspf+xml', name:'application/xspf+xml', ext:'xspf'},
        {abbr:'application/zip', name:'application/zip', ext:'zip'},
        {abbr:'application/vnd.3M.Post-it-Notes', name:'application/vnd.3M.Post-it-Notes'},
        {abbr:'application/vnd.accpac.simply.aso', name:'application/vnd.accpac.simply.aso'},
        {abbr:'application/vnd.accpac.simply.imp', name:'application/vnd.accpac.simply.imp'},
        {abbr:'application/vnd.acucobol', name:'application/vnd.acucobol'},
        {abbr:'application/vnd.aether.imp', name:'application/vnd.aether.imp'},
        {abbr:'application/vnd.android.package-archive', name:'application/vnd.android.package-archive', ext:'apk'},
        {abbr:'application/vnd.anser-web-certificate-issue-initiation', name:'application/vnd.anser-web-certificate-issue-initiation'},
        {abbr:'application/vnd.anser-web-funds-transfer-initiation', name:'application/vnd.anser-web-funds-transfer-initiation'},
        {abbr:'application/vnd.audiograph', name:'application/vnd.audiograph'},
        {abbr:'application/vnd.bmi', name:'application/vnd.bmi'},
        {abbr:'application/vnd.businessobjects', name:'application/vnd.businessobjects'},
        {abbr:'application/vnd.canon-cpdl', name:'application/vnd.canon-cpdl'},
        {abbr:'application/vnd.canon-lips', name:'application/vnd.canon-lips'},
        {abbr:'application/vnd.cinderella', name:'application/vnd.cinderella', ext:'cdy'},
        {abbr:'application/vnd.claymore', name:'application/vnd.claymore'},
        {abbr:'application/vnd.commerce-battelle', name:'application/vnd.commerce-battelle'},
        {abbr:'application/vnd.commonspace', name:'application/vnd.commonspace'},
        {abbr:'application/vnd.comsocaller', name:'application/vnd.comsocaller'},
        {abbr:'application/vnd.contact.cmsg', name:'application/vnd.contact.cmsg'},
        {abbr:'application/vnd.cosmocaller', name:'application/vnd.cosmocaller'},
        {abbr:'application/vnd.ctc-posml', name:'application/vnd.ctc-posml'},
        {abbr:'application/vnd.cups-postscript', name:'application/vnd.cups-postscript'},
        {abbr:'application/vnd.cups-raster', name:'application/vnd.cups-raster'},
        {abbr:'application/vnd.cups-raw', name:'application/vnd.cups-raw'},
        {abbr:'application/vnd.cybank', name:'application/vnd.cybank'},
        {abbr:'application/vnd.dna', name:'application/vnd.dna'},
        {abbr:'application/vnd.dpgraph', name:'application/vnd.dpgraph'},
        {abbr:'application/vnd.dxr', name:'application/vnd.dxr'},
        {abbr:'application/vnd.ecdis-update', name:'application/vnd.ecdis-update'},
        {abbr:'application/vnd.ecowin.chart', name:'application/vnd.ecowin.chart'},
        {abbr:'application/vnd.ecowin.filerequest', name:'application/vnd.ecowin.filerequest'},
        {abbr:'application/vnd.ecowin.fileupdate', name:'application/vnd.ecowin.fileupdate'},
        {abbr:'application/vnd.ecowin.series', name:'application/vnd.ecowin.series'},
        {abbr:'application/vnd.ecowin.seriesrequest', name:'application/vnd.ecowin.seriesrequest'},
        {abbr:'application/vnd.ecowin.seriesupdate', name:'application/vnd.ecowin.seriesupdate'},
        {abbr:'application/vnd.enliven', name:'application/vnd.enliven'},
        {abbr:'application/vnd.epson.esf', name:'application/vnd.epson.esf'},
        {abbr:'application/vnd.epson.msf', name:'application/vnd.epson.msf'},
        {abbr:'application/vnd.epson.quickanime', name:'application/vnd.epson.quickanime'},
        {abbr:'application/vnd.epson.salt', name:'application/vnd.epson.salt'},
        {abbr:'application/vnd.epson.ssf', name:'application/vnd.epson.ssf'},
        {abbr:'application/vnd.ericsson.quickcall', name:'application/vnd.ericsson.quickcall'},
        {abbr:'application/vnd.eudora.data', name:'application/vnd.eudora.data'},
        {abbr:'application/vnd.fdf', name:'application/vnd.fdf'},
        {abbr:'application/vnd.ffsns', name:'application/vnd.ffsns'},
        {abbr:'application/vnd.flographit', name:'application/vnd.flographit'},
        {abbr:'application/vnd.font-fontforge-sfd', name:'application/vnd.font-fontforge-sfd', ext:'sfd'},
        {abbr:'application/vnd.framemaker', name:'application/vnd.framemaker'},
        {abbr:'application/vnd.fsc.weblaunch', name:'application/vnd.fsc.weblaunch'},
        {abbr:'application/vnd.fujitsu.oasys', name:'application/vnd.fujitsu.oasys'},
        {abbr:'application/vnd.fujitsu.oasys2', name:'application/vnd.fujitsu.oasys2'},
        {abbr:'application/vnd.fujitsu.oasys3', name:'application/vnd.fujitsu.oasys3'},
        {abbr:'application/vnd.fujitsu.oasysgp', name:'application/vnd.fujitsu.oasysgp'},
        {abbr:'application/vnd.fujitsu.oasysprs', name:'application/vnd.fujitsu.oasysprs'},
        {abbr:'application/vnd.fujixerox.ddd', name:'application/vnd.fujixerox.ddd'},
        {abbr:'application/vnd.fujixerox.docuworks', name:'application/vnd.fujixerox.docuworks'},
        {abbr:'application/vnd.fujixerox.docuworks.binder', name:'application/vnd.fujixerox.docuworks.binder'},
        {abbr:'application/vnd.fut-misnet', name:'application/vnd.fut-misnet'},
        {abbr:'application/vnd.google-earth.kml+xml', name:'application/vnd.google-earth.kml+xml', ext:'kml'},
        {abbr:'application/vnd.google-earth.kmz', name:'application/vnd.google-earth.kmz', ext:'kmz'},
        {abbr:'application/vnd.grafeq', name:'application/vnd.grafeq'},
        {abbr:'application/vnd.groove-account', name:'application/vnd.groove-account'},
        {abbr:'application/vnd.groove-identity-message', name:'application/vnd.groove-identity-message'},
        {abbr:'application/vnd.groove-injector', name:'application/vnd.groove-injector'},
        {abbr:'application/vnd.groove-tool-message', name:'application/vnd.groove-tool-message'},
        {abbr:'application/vnd.groove-tool-template', name:'application/vnd.groove-tool-template'},
        {abbr:'application/vnd.groove-vcard', name:'application/vnd.groove-vcard'},
        {abbr:'application/vnd.hhe.lesson-player', name:'application/vnd.hhe.lesson-player'},
        {abbr:'application/vnd.hp-HPGL', name:'application/vnd.hp-HPGL'},
        {abbr:'application/vnd.hp-PCL', name:'application/vnd.hp-PCL'},
        {abbr:'application/vnd.hp-PCLXL', name:'application/vnd.hp-PCLXL'},
        {abbr:'application/vnd.hp-hpid', name:'application/vnd.hp-hpid'},
        {abbr:'application/vnd.hp-hps', name:'application/vnd.hp-hps'},
        {abbr:'application/vnd.httphone', name:'application/vnd.httphone'},
        {abbr:'application/vnd.hzn-3d-crossword', name:'application/vnd.hzn-3d-crossword'},
        {abbr:'application/vnd.ibm.MiniPay', name:'application/vnd.ibm.MiniPay'},
        {abbr:'application/vnd.ibm.afplinedata', name:'application/vnd.ibm.afplinedata'},
        {abbr:'application/vnd.ibm.modcap', name:'application/vnd.ibm.modcap'},
        {abbr:'application/vnd.informix-visionary', name:'application/vnd.informix-visionary'},
        {abbr:'application/vnd.intercon.formnet', name:'application/vnd.intercon.formnet'},
        {abbr:'application/vnd.intertrust.digibox', name:'application/vnd.intertrust.digibox'},
        {abbr:'application/vnd.intertrust.nncp', name:'application/vnd.intertrust.nncp'},
        {abbr:'application/vnd.intu.qbo', name:'application/vnd.intu.qbo'},
        {abbr:'application/vnd.intu.qfx', name:'application/vnd.intu.qfx'},
        {abbr:'application/vnd.irepository.package+xml', name:'application/vnd.irepository.package+xml'},
        {abbr:'application/vnd.is-xpr', name:'application/vnd.is-xpr'},
        {abbr:'application/vnd.japannet-directory-service', name:'application/vnd.japannet-directory-service'},
        {abbr:'application/vnd.japannet-jpnstore-wakeup', name:'application/vnd.japannet-jpnstore-wakeup'},
        {abbr:'application/vnd.japannet-payment-wakeup', name:'application/vnd.japannet-payment-wakeup'},
        {abbr:'application/vnd.japannet-registration', name:'application/vnd.japannet-registration'},
        {abbr:'application/vnd.japannet-registration-wakeup', name:'application/vnd.japannet-registration-wakeup'},
        {abbr:'application/vnd.japannet-setstore-wakeup', name:'application/vnd.japannet-setstore-wakeup'},
        {abbr:'application/vnd.japannet-verification', name:'application/vnd.japannet-verification'},
        {abbr:'application/vnd.japannet-verification-wakeup', name:'application/vnd.japannet-verification-wakeup'},
        {abbr:'application/vnd.koan', name:'application/vnd.koan'},
        {abbr:'application/vnd.lotus-1-2-3', name:'application/vnd.lotus-1-2-3'},
        {abbr:'application/vnd.lotus-approach', name:'application/vnd.lotus-approach'},
        {abbr:'application/vnd.lotus-freelance', name:'application/vnd.lotus-freelance'},
        {abbr:'application/vnd.lotus-notes', name:'application/vnd.lotus-notes'},
        {abbr:'application/vnd.lotus-organizer', name:'application/vnd.lotus-organizer'},
        {abbr:'application/vnd.lotus-screencam', name:'application/vnd.lotus-screencam'},
        {abbr:'application/vnd.lotus-wordpro', name:'application/vnd.lotus-wordpro'},
        {abbr:'application/vnd.mcd', name:'application/vnd.mcd'},
        {abbr:'application/vnd.mediastation.cdkey', name:'application/vnd.mediastation.cdkey'},
        {abbr:'application/vnd.meridian-slingshot', name:'application/vnd.meridian-slingshot'},
        {abbr:'application/vnd.mif', name:'application/vnd.mif'},
        {abbr:'application/vnd.minisoft-hp3000-save', name:'application/vnd.minisoft-hp3000-save'},
        {abbr:'application/vnd.mitsubishi.misty-guard.trustweb', name:'application/vnd.mitsubishi.misty-guard.trustweb'},
        {abbr:'application/vnd.mobius.daf', name:'application/vnd.mobius.daf'},
        {abbr:'application/vnd.mobius.dis', name:'application/vnd.mobius.dis'},
        {abbr:'application/vnd.mobius.msl', name:'application/vnd.mobius.msl'},
        {abbr:'application/vnd.mobius.plc', name:'application/vnd.mobius.plc'},
        {abbr:'application/vnd.mobius.txf', name:'application/vnd.mobius.txf'},
        {abbr:'application/vnd.motorola.flexsuite', name:'application/vnd.motorola.flexsuite'},
        {abbr:'application/vnd.motorola.flexsuite.adsi', name:'application/vnd.motorola.flexsuite.adsi'},
        {abbr:'application/vnd.motorola.flexsuite.fis', name:'application/vnd.motorola.flexsuite.fis'},
        {abbr:'application/vnd.motorola.flexsuite.gotap', name:'application/vnd.motorola.flexsuite.gotap'},
        {abbr:'application/vnd.motorola.flexsuite.kmr', name:'application/vnd.motorola.flexsuite.kmr'},
        {abbr:'application/vnd.motorola.flexsuite.ttc', name:'application/vnd.motorola.flexsuite.ttc'},
        {abbr:'application/vnd.motorola.flexsuite.wem', name:'application/vnd.motorola.flexsuite.wem'},
        {abbr:'application/vnd.mozilla.xul+xml', name:'application/vnd.mozilla.xul+xml', ext:'xul'},
        {abbr:'application/vnd.ms-artgalry', name:'application/vnd.ms-artgalry'},
        {abbr:'application/vnd.ms-asf', name:'application/vnd.ms-asf'},
        {abbr:'application/vnd.ms-excel', name:'application/vnd.ms-excel', ext:'xls'},
        {abbr:'application/vnd.ms-excel.addin.macroEnabled.12', name:'application/vnd.ms-excel.addin.macroEnabled.12', ext:'xlam'},
        {abbr:'application/vnd.ms-excel.sheet.binary.macroEnabled.12', name:'application/vnd.ms-excel.sheet.binary.macroEnabled.12', ext:'xlsb'},
        {abbr:'application/vnd.ms-excel.sheet.macroEnabled.12', name:'application/vnd.ms-excel.sheet.macroEnabled.12', ext:'xlsm'},
        {abbr:'application/vnd.ms-excel.template.macroEnabled.12', name:'application/vnd.ms-excel.template.macroEnabled.12', ext:'xltm'},
        {abbr:'application/vnd.ms-fontobject', name:'application/vnd.ms-fontobject', ext:'eot'},
        {abbr:'application/vnd.ms-lrm', name:'application/vnd.ms-lrm'},
        {abbr:'application/vnd.ms-officetheme', name:'application/vnd.ms-officetheme', ext:'thmx'},
        {abbr:'application/vnd.ms-pki.seccat', name:'application/vnd.ms-pki.seccat', ext:'cat'},
        {abbr:'application/vnd.ms-pki.stl', name:'application/vnd.ms-pki.stl', ext:'stl'},
        {abbr:'application/vnd.ms-powerpoint', name:'application/vnd.ms-powerpoint', ext:'ppt'},
        {abbr:'application/vnd.ms-powerpoint.addin.macroEnabled.12', name:'application/vnd.ms-powerpoint.addin.macroEnabled.12', ext:'ppam'},
        {abbr:'application/vnd.ms-powerpoint.presentation.macroEnabled.12', name:'application/vnd.ms-powerpoint.presentation.macroEnabled.12', ext:'pptm'},
        {abbr:'application/vnd.ms-powerpoint.slide.macroEnabled.12', name:'application/vnd.ms-powerpoint.slide.macroEnabled.12', ext:'sldm'},
        {abbr:'application/vnd.ms-powerpoint.slideshow.macroEnabled.12', name:'application/vnd.ms-powerpoint.slideshow.macroEnabled.12', ext:'ppsm'},
        {abbr:'application/vnd.ms-powerpoint.template.macroEnabled.12', name:'application/vnd.ms-powerpoint.template.macroEnabled.12', ext:'potm'},
        {abbr:'application/vnd.ms-project', name:'application/vnd.ms-project'},
        {abbr:'application/vnd.ms-tnef', name:'application/vnd.ms-tnef'},
        {abbr:'application/vnd.ms-word.document.macroEnabled.12', name:'application/vnd.ms-word.document.macroEnabled.12', ext:'docm'},
        {abbr:'application/vnd.ms-word.template.macroEnabled.12', name:'application/vnd.ms-word.template.macroEnabled.12', ext:'dotm'},
        {abbr:'application/vnd.ms-works', name:'application/vnd.ms-works'},
        {abbr:'application/vnd.mseq', name:'application/vnd.mseq'},
        {abbr:'application/vnd.msign', name:'application/vnd.msign'},
        {abbr:'application/vnd.music-niff', name:'application/vnd.music-niff'},
        {abbr:'application/vnd.musician', name:'application/vnd.musician'},
        {abbr:'application/vnd.netfpx', name:'application/vnd.netfpx'},
        {abbr:'application/vnd.noblenet-directory', name:'application/vnd.noblenet-directory'},
        {abbr:'application/vnd.noblenet-sealer', name:'application/vnd.noblenet-sealer'},
        {abbr:'application/vnd.noblenet-web', name:'application/vnd.noblenet-web'},
        {abbr:'application/vnd.novadigm.EDM', name:'application/vnd.novadigm.EDM'},
        {abbr:'application/vnd.novadigm.EDX', name:'application/vnd.novadigm.EDX'},
        {abbr:'application/vnd.novadigm.EXT', name:'application/vnd.novadigm.EXT'},
        {abbr:'application/vnd.oasis.opendocument.chart', name:'application/vnd.oasis.opendocument.chart', ext:'odc'},
        {abbr:'application/vnd.oasis.opendocument.database', name:'application/vnd.oasis.opendocument.database', ext:'odb'},
        {abbr:'application/vnd.oasis.opendocument.formula', name:'application/vnd.oasis.opendocument.formula', ext:'odf'},
        {abbr:'application/vnd.oasis.opendocument.graphics', name:'application/vnd.oasis.opendocument.graphics', ext:'odg'},
        {abbr:'application/vnd.oasis.opendocument.graphics-template', name:'application/vnd.oasis.opendocument.graphics-template', ext:'otg'},
        {abbr:'application/vnd.oasis.opendocument.image', name:'application/vnd.oasis.opendocument.image', ext:'odi'},
        {abbr:'application/vnd.oasis.opendocument.presentation', name:'application/vnd.oasis.opendocument.presentation', ext:'odp'},
        {abbr:'application/vnd.oasis.opendocument.presentation-template', name:'application/vnd.oasis.opendocument.presentation-template', ext:'otp'},
        {abbr:'application/vnd.oasis.opendocument.spreadsheet', name:'application/vnd.oasis.opendocument.spreadsheet', ext:'ods'},
        {abbr:'application/vnd.oasis.opendocument.spreadsheet-template', name:'application/vnd.oasis.opendocument.spreadsheet-template', ext:'ots'},
        {abbr:'application/vnd.oasis.opendocument.text', name:'application/vnd.oasis.opendocument.text', ext:'odt'},
        {abbr:'application/vnd.oasis.opendocument.text-master', name:'application/vnd.oasis.opendocument.text-master', ext:'odm'},
        {abbr:'application/vnd.oasis.opendocument.text-template', name:'application/vnd.oasis.opendocument.text-template', ext:'ott'},
        {abbr:'application/vnd.oasis.opendocument.text-web', name:'application/vnd.oasis.opendocument.text-web', ext:'oth'},
        {abbr:'application/vnd.openxmlformats-officedocument.presentationml.presentation', name:'application/vnd.openxmlformats-officedocument.presentationml.presentation', ext:'pptx'},
        {abbr:'application/vnd.openxmlformats-officedocument.presentationml.slide', name:'application/vnd.openxmlformats-officedocument.presentationml.slide', ext:'sldx'},
        {abbr:'application/vnd.openxmlformats-officedocument.presentationml.slideshow', name:'application/vnd.openxmlformats-officedocument.presentationml.slideshow', ext:'ppsx'},
        {abbr:'application/vnd.openxmlformats-officedocument.presentationml.template', name:'application/vnd.openxmlformats-officedocument.presentationml.template', ext:'potx'},
        {abbr:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', name:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', ext:'xlsx'},
        {abbr:'application/vnd.openxmlformats-officedocument.spreadsheetml.template', name:'application/vnd.openxmlformats-officedocument.spreadsheetml.template', ext:'xltx'},
        {abbr:'application/vnd.openxmlformats-officedocument.wordprocessingml.document', name:'application/vnd.openxmlformats-officedocument.wordprocessingml.document', ext:'docx'},
        {abbr:'application/vnd.openxmlformats-officedocument.wordprocessingml.template', name:'application/vnd.openxmlformats-officedocument.wordprocessingml.template', ext:'dotx'},
        {abbr:'application/vnd.osa.netdeploy', name:'application/vnd.osa.netdeploy'},
        {abbr:'application/vnd.palm', name:'application/vnd.palm'},
        {abbr:'application/vnd.pg.format', name:'application/vnd.pg.format'},
        {abbr:'application/vnd.pg.osasli', name:'application/vnd.pg.osasli'},
        {abbr:'application/vnd.powerbuilder6', name:'application/vnd.powerbuilder6'},
        {abbr:'application/vnd.powerbuilder6-s', name:'application/vnd.powerbuilder6-s'},
        {abbr:'application/vnd.powerbuilder7', name:'application/vnd.powerbuilder7'},
        {abbr:'application/vnd.powerbuilder7-s', name:'application/vnd.powerbuilder7-s'},
        {abbr:'application/vnd.powerbuilder75', name:'application/vnd.powerbuilder75'},
        {abbr:'application/vnd.powerbuilder75-s', name:'application/vnd.powerbuilder75-s'},
        {abbr:'application/vnd.previewsystems.box', name:'application/vnd.previewsystems.box'},
        {abbr:'application/vnd.publishare-delta-tree', name:'application/vnd.publishare-delta-tree'},
        {abbr:'application/vnd.pvi.ptid1', name:'application/vnd.pvi.ptid1'},
        {abbr:'application/vnd.pwg-xhtml-print+xml', name:'application/vnd.pwg-xhtml-print+xml'},
        {abbr:'application/vnd.rapid', name:'application/vnd.rapid'},
        {abbr:'application/vnd.rim.cod', name:'application/vnd.rim.cod', ext:'cod'},
        {abbr:'application/vnd.s3sms', name:'application/vnd.s3sms'},
        {abbr:'application/vnd.seemail', name:'application/vnd.seemail'},
        {abbr:'application/vnd.shana.informed.formdata', name:'application/vnd.shana.informed.formdata'},
        {abbr:'application/vnd.shana.informed.formtemplate', name:'application/vnd.shana.informed.formtemplate'},
        {abbr:'application/vnd.shana.informed.interchange', name:'application/vnd.shana.informed.interchange'},
        {abbr:'application/vnd.shana.informed.package', name:'application/vnd.shana.informed.package'},
        {abbr:'application/vnd.smaf', name:'application/vnd.smaf', ext:'mmf'},
        {abbr:'application/vnd.sss-cod', name:'application/vnd.sss-cod'},
        {abbr:'application/vnd.sss-dtf', name:'application/vnd.sss-dtf'},
        {abbr:'application/vnd.sss-ntf', name:'application/vnd.sss-ntf'},
        {abbr:'application/vnd.stardivision.calc', name:'application/vnd.stardivision.calc', ext:'sdc'},
        {abbr:'application/vnd.stardivision.chart', name:'application/vnd.stardivision.chart', ext:'sds'},
        {abbr:'application/vnd.stardivision.draw', name:'application/vnd.stardivision.draw', ext:'sda'},
        {abbr:'application/vnd.stardivision.impress', name:'application/vnd.stardivision.impress', ext:'sdd'},
        {abbr:'application/vnd.stardivision.math', name:'application/vnd.stardivision.math', ext:'sdf'},
        {abbr:'application/vnd.stardivision.writer', name:'application/vnd.stardivision.writer', ext:'sdw'},
        {abbr:'application/vnd.stardivision.writer-global', name:'application/vnd.stardivision.writer-global', ext:'sgl'},
        {abbr:'application/vnd.street-stream', name:'application/vnd.street-stream'},
        {abbr:'application/vnd.sun.xml.calc', name:'application/vnd.sun.xml.calc', ext:'sxc'},
        {abbr:'application/vnd.sun.xml.calc.template', name:'application/vnd.sun.xml.calc.template', ext:'stc'},
        {abbr:'application/vnd.sun.xml.draw', name:'application/vnd.sun.xml.draw', ext:'sxd'},
        {abbr:'application/vnd.sun.xml.draw.template', name:'application/vnd.sun.xml.draw.template', ext:'std'},
        {abbr:'application/vnd.sun.xml.impress', name:'application/vnd.sun.xml.impress', ext:'sxi'},
        {abbr:'application/vnd.sun.xml.impress.template', name:'application/vnd.sun.xml.impress.template', ext:'sti'},
        {abbr:'application/vnd.sun.xml.math', name:'application/vnd.sun.xml.math', ext:'sxm'},
        {abbr:'application/vnd.sun.xml.writer', name:'application/vnd.sun.xml.writer', ext:'sxw'},
        {abbr:'application/vnd.sun.xml.writer.global', name:'application/vnd.sun.xml.writer.global', ext:'sxg'},
        {abbr:'application/vnd.sun.xml.writer.template', name:'application/vnd.sun.xml.writer.template', ext:'stw'},
        {abbr:'application/vnd.svd', name:'application/vnd.svd'},
        {abbr:'application/vnd.swiftview-ics', name:'application/vnd.swiftview-ics'},
        {abbr:'application/vnd.symbian.install', name:'application/vnd.symbian.install', ext:'sis'},
        {abbr:'application/vnd.tcpdump.pcap', name:'application/vnd.tcpdump.pcap', ext:'cap'},
        {abbr:'application/vnd.triscape.mxs', name:'application/vnd.triscape.mxs'},
        {abbr:'application/vnd.trueapp', name:'application/vnd.trueapp'},
        {abbr:'application/vnd.truedoc', name:'application/vnd.truedoc'},
        {abbr:'application/vnd.tve-trigger', name:'application/vnd.tve-trigger'},
        {abbr:'application/vnd.ufdl', name:'application/vnd.ufdl'},
        {abbr:'application/vnd.uplanet.alert', name:'application/vnd.uplanet.alert'},
        {abbr:'application/vnd.uplanet.alert-wbxml', name:'application/vnd.uplanet.alert-wbxml'},
        {abbr:'application/vnd.uplanet.bearer-choice', name:'application/vnd.uplanet.bearer-choice'},
        {abbr:'application/vnd.uplanet.bearer-choice-wbxml', name:'application/vnd.uplanet.bearer-choice-wbxml'},
        {abbr:'application/vnd.uplanet.cacheop', name:'application/vnd.uplanet.cacheop'},
        {abbr:'application/vnd.uplanet.cacheop-wbxml', name:'application/vnd.uplanet.cacheop-wbxml'},
        {abbr:'application/vnd.uplanet.channel', name:'application/vnd.uplanet.channel'},
        {abbr:'application/vnd.uplanet.channel-wbxml', name:'application/vnd.uplanet.channel-wbxml'},
        {abbr:'application/vnd.uplanet.list', name:'application/vnd.uplanet.list'},
        {abbr:'application/vnd.uplanet.list-wbxml', name:'application/vnd.uplanet.list-wbxml'},
        {abbr:'application/vnd.uplanet.listcmd', name:'application/vnd.uplanet.listcmd'},
        {abbr:'application/vnd.uplanet.listcmd-wbxml', name:'application/vnd.uplanet.listcmd-wbxml'},
        {abbr:'application/vnd.uplanet.signal', name:'application/vnd.uplanet.signal'},
        {abbr:'application/vnd.vcx', name:'application/vnd.vcx'},
        {abbr:'application/vnd.vectorworks', name:'application/vnd.vectorworks'},
        {abbr:'application/vnd.vidsoft.vidconference', name:'application/vnd.vidsoft.vidconference'},
        {abbr:'application/vnd.visio', name:'application/vnd.visio', ext:'vsd'},
        {abbr:'application/vnd.vividence.scriptfile', name:'application/vnd.vividence.scriptfile'},
        {abbr:'application/vnd.wap.sic', name:'application/vnd.wap.sic'},
        {abbr:'application/vnd.wap.slc', name:'application/vnd.wap.slc'},
        {abbr:'application/vnd.wap.wbxml', name:'application/vnd.wap.wbxml', ext:'wbxml'},
        {abbr:'application/vnd.wap.wmlc', name:'application/vnd.wap.wmlc', ext:'wmlc'},
        {abbr:'application/vnd.wap.wmlscriptc', name:'application/vnd.wap.wmlscriptc', ext:'wmlsc'},
        {abbr:'application/vnd.webturbo', name:'application/vnd.webturbo'},
        {abbr:'application/vnd.wordperfect', name:'application/vnd.wordperfect', ext:'wpd'},
        {abbr:'application/vnd.wordperfect5.1', name:'application/vnd.wordperfect5.1', ext:'wp5'},
        {abbr:'application/vnd.wrq-hp3000-labelled', name:'application/vnd.wrq-hp3000-labelled'},
        {abbr:'application/vnd.wt.stf', name:'application/vnd.wt.stf'},
        {abbr:'application/vnd.xara', name:'application/vnd.xara'},
        {abbr:'application/vnd.xfdl', name:'application/vnd.xfdl'},
        {abbr:'application/vnd.yellowriver-custom-menu', name:'application/vnd.yellowriver-custom-menu'},
        {abbr:'application/zlib', name:'application/zlib'},
        {abbr:'application/x-123', name:'application/x-123', ext:'wk'},
        {abbr:'application/x-7z-compressed', name:'application/x-7z-compressed', ext:'7z'},
        {abbr:'application/x-abiword', name:'application/x-abiword', ext:'abw'},
        {abbr:'application/x-apple-diskimage', name:'application/x-apple-diskimage', ext:'dmg'},
        {abbr:'application/x-bcpio', name:'application/x-bcpio', ext:'bcpio'},
        {abbr:'application/x-bittorrent', name:'application/x-bittorrent', ext:'torrent'},
        {abbr:'application/x-cab', name:'application/x-cab', ext:'cab'},
        {abbr:'application/x-cbr', name:'application/x-cbr', ext:'cbr'},
        {abbr:'application/x-cbz', name:'application/x-cbz', ext:'cbz'},
        {abbr:'application/x-cdf', name:'application/x-cdf', ext:'cdf'},
        {abbr:'application/x-cdlink', name:'application/x-cdlink', ext:'vcd'},
        {abbr:'application/x-chess-pgn', name:'application/x-chess-pgn', ext:'pgn'},
        {abbr:'application/x-comsol', name:'application/x-comsol', ext:'mph'},
        {abbr:'application/x-core', name:'application/x-core'},
        {abbr:'application/x-cpio', name:'application/x-cpio', ext:'cpio'},
        {abbr:'application/x-csh', name:'application/x-csh', ext:'csh'},
        {abbr:'application/x-debian-package', name:'application/x-debian-package', ext:'deb'},
        {abbr:'application/x-director', name:'application/x-director', ext:'dcr'},
        {abbr:'application/x-dms', name:'application/x-dms', ext:'dms'},
        {abbr:'application/x-doom', name:'application/x-doom', ext:'wad'},
        {abbr:'application/x-dvi', name:'application/x-dvi', ext:'dvi'},
        {abbr:'application/x-executable', name:'application/x-executable'},
        {abbr:'application/x-font', name:'application/x-font', ext:'pfa'},
        {abbr:'application/x-font-pcf', name:'application/x-font-pcf', ext:'pcf'},
        {abbr:'application/x-freemind', name:'application/x-freemind', ext:'mm'},
        {abbr:'application/x-futuresplash', name:'application/x-futuresplash', ext:'spl'},
        {abbr:'application/x-ganttproject', name:'application/x-ganttproject', ext:'gan'},
        {abbr:'application/x-gnumeric', name:'application/x-gnumeric', ext:'gnumeric'},
        {abbr:'application/x-go-sgf', name:'application/x-go-sgf', ext:'sgf'},
        {abbr:'application/x-graphing-calculator', name:'application/x-graphing-calculator', ext:'gcf'},
        {abbr:'application/x-gtar', name:'application/x-gtar', ext:'gtar'},
        {abbr:'application/x-gtar-compressed', name:'application/x-gtar-compressed', ext:'tgz'},
        {abbr:'application/x-hdf', name:'application/x-hdf', ext:'hdf'},
        {abbr:'application/x-httpd-eruby', name:'application/x-httpd-eruby', ext:'rhtml'},
        {abbr:'application/x-httpd-php', name:'application/x-httpd-php', ext:'phtml'},
        {abbr:'application/x-httpd-php-source', name:'application/x-httpd-php-source', ext:'phps'},
        {abbr:'application/x-httpd-php3', name:'application/x-httpd-php3', ext:'php3'},
        {abbr:'application/x-httpd-php3-preprocessed', name:'application/x-httpd-php3-preprocessed', ext:'php3p'},
        {abbr:'application/x-httpd-php4', name:'application/x-httpd-php4', ext:'php4'},
        {abbr:'application/x-httpd-php5', name:'application/x-httpd-php5', ext:'php5'},
        {abbr:'application/x-hwp', name:'application/x-hwp', ext:'hwp'},
        {abbr:'application/x-ica', name:'application/x-ica', ext:'ica'},
        {abbr:'application/x-info', name:'application/x-info', ext:'info'},
        {abbr:'application/x-internet-signup', name:'application/x-internet-signup', ext:'ins'},
        {abbr:'application/x-iphone', name:'application/x-iphone', ext:'iii'},
        {abbr:'application/x-iso9660-image', name:'application/x-iso9660-image', ext:'iso'},
        {abbr:'application/x-jam', name:'application/x-jam', ext:'jam'},
        {abbr:'application/x-java-applet', name:'application/x-java-applet'},
        {abbr:'application/x-java-bean', name:'application/x-java-bean'},
        {abbr:'application/x-java-jnlp-file', name:'application/x-java-jnlp-file', ext:'jnlp'},
        {abbr:'application/x-jmol', name:'application/x-jmol', ext:'jmz'},
        {abbr:'application/x-kchart', name:'application/x-kchart', ext:'chrt'},
        {abbr:'application/x-kdelnk', name:'application/x-kdelnk'},
        {abbr:'application/x-killustrator', name:'application/x-killustrator', ext:'kil'},
        {abbr:'application/x-koan', name:'application/x-koan', ext:'skp'},
        {abbr:'application/x-kpresenter', name:'application/x-kpresenter', ext:'kpr'},
        {abbr:'application/x-kspread', name:'application/x-kspread', ext:'ksp'},
        {abbr:'application/x-kword', name:'application/x-kword', ext:'kwd'},
        {abbr:'application/x-latex', name:'application/x-latex', ext:'latex'},
        {abbr:'application/x-lha', name:'application/x-lha', ext:'lha'},
        {abbr:'application/x-lyx', name:'application/x-lyx', ext:'lyx'},
        {abbr:'application/x-lzh', name:'application/x-lzh', ext:'lzh'},
        {abbr:'application/x-lzx', name:'application/x-lzx', ext:'lzx'},
        {abbr:'application/x-maker', name:'application/x-maker', ext:'frm'},
        {abbr:'application/x-mif', name:'application/x-mif', ext:'mif'},
        {abbr:'application/x-mpegURL', name:'application/x-mpegURL', ext:'m3u8'},
        {abbr:'application/x-ms-wmd', name:'application/x-ms-wmd', ext:'wmd'},
        {abbr:'application/x-ms-wmz', name:'application/x-ms-wmz', ext:'wmz'},
        {abbr:'application/x-msdos-program', name:'application/x-msdos-program', ext:'com'},
        {abbr:'application/x-msi', name:'application/x-msi', ext:'msi'},
        {abbr:'application/x-netcdf', name:'application/x-netcdf', ext:'nc'},
        {abbr:'application/x-ns-proxy-autoconfig', name:'application/x-ns-proxy-autoconfig', ext:'pac'},
        {abbr:'application/x-nwc', name:'application/x-nwc', ext:'nwc'},
        {abbr:'application/x-object', name:'application/x-object', ext:'o'},
        {abbr:'application/x-oz-application', name:'application/x-oz-application', ext:'oza'},
        {abbr:'application/x-pkcs7-certreqresp', name:'application/x-pkcs7-certreqresp', ext:'p7r'},
        {abbr:'application/x-pkcs7-crl', name:'application/x-pkcs7-crl', ext:'crl'},
        {abbr:'application/x-python-code', name:'application/x-python-code', ext:'pyc'},
        {abbr:'application/x-qgis', name:'application/x-qgis', ext:'qgs'},
        {abbr:'application/x-quicktimeplayer', name:'application/x-quicktimeplayer', ext:'qtl'},
        {abbr:'application/x-rdp', name:'application/x-rdp', ext:'rdp'},
        {abbr:'application/x-redhat-package-manager', name:'application/x-redhat-package-manager', ext:'rpm'},
        {abbr:'application/x-rss+xml', name:'application/x-rss+xml', ext:'rss'},
        {abbr:'application/x-ruby', name:'application/x-ruby', ext:'rb'},
        {abbr:'application/x-rx', name:'application/x-rx'},
        {abbr:'application/x-scilab', name:'application/x-scilab', ext:'sci'},
        {abbr:'application/x-scilab-xcos', name:'application/x-scilab-xcos', ext:'xcos'},
        {abbr:'application/x-sh', name:'application/x-sh', ext:'sh'},
        {abbr:'application/x-shar', name:'application/x-shar', ext:'shar'},
        {abbr:'application/x-shellscript', name:'application/x-shellscript'},
        {abbr:'application/x-shockwave-flash', name:'application/x-shockwave-flash', ext:'swf'},
        {abbr:'application/x-silverlight', name:'application/x-silverlight', ext:'scr'},
        {abbr:'application/x-sql', name:'application/x-sql', ext:'sql'},
        {abbr:'application/x-stuffit', name:'application/x-stuffit', ext:'sit'},
        {abbr:'application/x-sv4cpio', name:'application/x-sv4cpio', ext:'sv4cpio'},
        {abbr:'application/x-sv4crc', name:'application/x-sv4crc', ext:'sv4crc'},
        {abbr:'application/x-tar', name:'application/x-tar', ext:'tar'},
        {abbr:'application/x-tcl', name:'application/x-tcl', ext:'tcl'},
        {abbr:'application/x-tex-gf', name:'application/x-tex-gf', ext:'gf'},
        {abbr:'application/x-tex-pk', name:'application/x-tex-pk', ext:'pk'},
        {abbr:'application/x-texinfo', name:'application/x-texinfo', ext:'texinfo'},
        {abbr:'application/x-trash', name:'application/x-trash', ext:'~'},
        {abbr:'application/x-troff', name:'application/x-troff', ext:'t'},
        {abbr:'application/x-troff-man', name:'application/x-troff-man', ext:'man'},
        {abbr:'application/x-troff-me', name:'application/x-troff-me', ext:'me'},
        {abbr:'application/x-troff-ms', name:'application/x-troff-ms', ext:'ms'},
        {abbr:'application/x-ustar', name:'application/x-ustar', ext:'ustar'},
        {abbr:'application/x-videolan', name:'application/x-videolan'},
        {abbr:'application/x-wais-source', name:'application/x-wais-source', ext:'src'},
        {abbr:'application/x-wingz', name:'application/x-wingz', ext:'wz'},
        {abbr:'application/x-x509-ca-cert', name:'application/x-x509-ca-cert', ext:'crt'},
        {abbr:'application/x-xcf', name:'application/x-xcf', ext:'xcf'},
        {abbr:'application/x-xfig', name:'application/x-xfig', ext:'fig'},
        {abbr:'application/x-xpinstall', name:'application/x-xpinstall', ext:'xpi'},
        {abbr:'audio/32kadpcm', name:'audio/32kadpcm'},
        {abbr:'audio/3gpp', name:'audio/3gpp'},
        {abbr:'audio/amr', name:'audio/amr', ext:'amr'},
        {abbr:'audio/amr-wb', name:'audio/amr-wb', ext:'awb'},
        {abbr:'audio/annodex', name:'audio/annodex', ext:'axa'},
        {abbr:'audio/basic', name:'audio/basic', ext:'au'},
        {abbr:'audio/csound', name:'audio/csound', ext:'csd'},
        {abbr:'audio/flac', name:'audio/flac', ext:'flac'},
        {abbr:'audio/g.722.1', name:'audio/g.722.1'},
        {abbr:'audio/l16', name:'audio/l16'},
        {abbr:'audio/midi', name:'audio/midi', ext:'mid'},
        {abbr:'audio/mp4a-latm', name:'audio/mp4a-latm'},
        {abbr:'audio/mpa-robust', name:'audio/mpa-robust'},
        {abbr:'audio/mpeg', name:'audio/mpeg', ext:'mpga'},
        {abbr:'audio/mpegurl', name:'audio/mpegurl', ext:'m3u'},
        {abbr:'audio/ogg', name:'audio/ogg', ext:'oga'},
        {abbr:'audio/parityfec', name:'audio/parityfec'},
        {abbr:'audio/prs.sid', name:'audio/prs.sid', ext:'sid'},
        {abbr:'audio/telephone-event', name:'audio/telephone-event'},
        {abbr:'audio/tone', name:'audio/tone'},
        {abbr:'audio/vnd.cisco.nse', name:'audio/vnd.cisco.nse'},
        {abbr:'audio/vnd.cns.anp1', name:'audio/vnd.cns.anp1'},
        {abbr:'audio/vnd.cns.inf1', name:'audio/vnd.cns.inf1'},
        {abbr:'audio/vnd.digital-winds', name:'audio/vnd.digital-winds'},
        {abbr:'audio/vnd.everad.plj', name:'audio/vnd.everad.plj'},
        {abbr:'audio/vnd.lucent.voice', name:'audio/vnd.lucent.voice'},
        {abbr:'audio/vnd.nortel.vbk', name:'audio/vnd.nortel.vbk'},
        {abbr:'audio/vnd.nuera.ecelp4800', name:'audio/vnd.nuera.ecelp4800'},
        {abbr:'audio/vnd.nuera.ecelp7470', name:'audio/vnd.nuera.ecelp7470'},
        {abbr:'audio/vnd.nuera.ecelp9600', name:'audio/vnd.nuera.ecelp9600'},
        {abbr:'audio/vnd.octel.sbc', name:'audio/vnd.octel.sbc'},
        {abbr:'audio/vnd.qcelp', name:'audio/vnd.qcelp'},
        {abbr:'audio/vnd.rhetorex.32kadpcm', name:'audio/vnd.rhetorex.32kadpcm'},
        {abbr:'audio/vnd.vmx.cvsd', name:'audio/vnd.vmx.cvsd'},
        {abbr:'audio/x-aiff', name:'audio/x-aiff', ext:'aif'},
        {abbr:'audio/x-gsm', name:'audio/x-gsm', ext:'gsm'},
        {abbr:'audio/x-mpegurl', name:'audio/x-mpegurl', ext:'m3u'},
        {abbr:'audio/x-ms-wma', name:'audio/x-ms-wma', ext:'wma'},
        {abbr:'audio/x-ms-wax', name:'audio/x-ms-wax', ext:'wax'},
        {abbr:'audio/x-pn-realaudio-plugin', name:'audio/x-pn-realaudio-plugin'},
        {abbr:'audio/x-pn-realaudio', name:'audio/x-pn-realaudio', ext:'ra'},
        {abbr:'audio/x-realaudio', name:'audio/x-realaudio', ext:'ra'},
        {abbr:'audio/x-scpls', name:'audio/x-scpls', ext:'pls'},
        {abbr:'audio/x-sd2', name:'audio/x-sd2', ext:'sd2'},
        {abbr:'audio/x-wav', name:'audio/x-wav', ext:'wav'},
        {abbr:'chemical/x-alchemy', name:'chemical/x-alchemy', ext:'alc'},
        {abbr:'chemical/x-cache', name:'chemical/x-cache', ext:'cac'},
        {abbr:'chemical/x-cache-csf', name:'chemical/x-cache-csf', ext:'csf'},
        {abbr:'chemical/x-cactvs-binary', name:'chemical/x-cactvs-binary', ext:'cbin'},
        {abbr:'chemical/x-cdx', name:'chemical/x-cdx', ext:'cdx'},
        {abbr:'chemical/x-cerius', name:'chemical/x-cerius', ext:'cer'},
        {abbr:'chemical/x-chem3d', name:'chemical/x-chem3d', ext:'c3d'},
        {abbr:'chemical/x-chemdraw', name:'chemical/x-chemdraw', ext:'chm'},
        {abbr:'chemical/x-cif', name:'chemical/x-cif', ext:'cif'},
        {abbr:'chemical/x-cmdf', name:'chemical/x-cmdf', ext:'cmdf'},
        {abbr:'chemical/x-cml', name:'chemical/x-cml', ext:'cml'},
        {abbr:'chemical/x-compass', name:'chemical/x-compass', ext:'cpa'},
        {abbr:'chemical/x-crossfire', name:'chemical/x-crossfire', ext:'bsd'},
        {abbr:'chemical/x-csml', name:'chemical/x-csml', ext:'csml'},
        {abbr:'chemical/x-ctx', name:'chemical/x-ctx', ext:'ctx'},
        {abbr:'chemical/x-cxf', name:'chemical/x-cxf', ext:'cxf'},
        {abbr:'chemical/x-daylight-smiles', name:'chemical/x-daylight-smiles', ext:'smi'},
        {abbr:'chemical/x-embl-dl-nucleotide', name:'chemical/x-embl-dl-nucleotide', ext:'emb'},
        {abbr:'chemical/x-galactic-spc', name:'chemical/x-galactic-spc', ext:'spc'},
        {abbr:'chemical/x-gamess-input', name:'chemical/x-gamess-input', ext:'inp'},
        {abbr:'chemical/x-gaussian-checkpoint', name:'chemical/x-gaussian-checkpoint', ext:'fch'},
        {abbr:'chemical/x-gaussian-cube', name:'chemical/x-gaussian-cube', ext:'cub'},
        {abbr:'chemical/x-gaussian-input', name:'chemical/x-gaussian-input', ext:'gau'},
        {abbr:'chemical/x-gaussian-log', name:'chemical/x-gaussian-log', ext:'gal'},
        {abbr:'chemical/x-gcg8-sequence', name:'chemical/x-gcg8-sequence', ext:'gcg'},
        {abbr:'chemical/x-genbank', name:'chemical/x-genbank', ext:'gen'},
        {abbr:'chemical/x-hin', name:'chemical/x-hin', ext:'hin'},
        {abbr:'chemical/x-isostar', name:'chemical/x-isostar', ext:'istr'},
        {abbr:'chemical/x-jcamp-dx', name:'chemical/x-jcamp-dx', ext:'jdx'},
        {abbr:'chemical/x-kinemage', name:'chemical/x-kinemage', ext:'kin'},
        {abbr:'chemical/x-macmolecule', name:'chemical/x-macmolecule', ext:'mcm'},
        {abbr:'chemical/x-macromodel-input', name:'chemical/x-macromodel-input', ext:'mmd'},
        {abbr:'chemical/x-mdl-molfile', name:'chemical/x-mdl-molfile', ext:'mol'},
        {abbr:'chemical/x-mdl-rdfile', name:'chemical/x-mdl-rdfile', ext:'rd'},
        {abbr:'chemical/x-mdl-rxnfile', name:'chemical/x-mdl-rxnfile', ext:'rxn'},
        {abbr:'chemical/x-mdl-sdfile', name:'chemical/x-mdl-sdfile', ext:'sd'},
        {abbr:'chemical/x-mdl-tgf', name:'chemical/x-mdl-tgf', ext:'tgf'},
        {abbr:'chemical/x-mif', name:'chemical/x-mif', ext:'mif'},
        {abbr:'chemical/x-mmcif', name:'chemical/x-mmcif', ext:'mcif'},
        {abbr:'chemical/x-mol2', name:'chemical/x-mol2', ext:'mol2'},
        {abbr:'chemical/x-molconn-Z', name:'chemical/x-molconn-Z', ext:'b'},
        {abbr:'chemical/x-mopac-graph', name:'chemical/x-mopac-graph', ext:'gpt'},
        {abbr:'chemical/x-mopac-input', name:'chemical/x-mopac-input', ext:'mop'},
        {abbr:'chemical/x-mopac-out', name:'chemical/x-mopac-out', ext:'moo'},
        {abbr:'chemical/x-mopac-vib', name:'chemical/x-mopac-vib', ext:'mvb'},
        {abbr:'chemical/x-ncbi-asn1', name:'chemical/x-ncbi-asn1', ext:'asn'},
        {abbr:'chemical/x-ncbi-asn1-ascii', name:'chemical/x-ncbi-asn1-ascii', ext:'prt'},
        {abbr:'chemical/x-ncbi-asn1-binary', name:'chemical/x-ncbi-asn1-binary', ext:'val'},
        {abbr:'chemical/x-ncbi-asn1-spec', name:'chemical/x-ncbi-asn1-spec', ext:'asn'},
        {abbr:'chemical/x-pdb', name:'chemical/x-pdb', ext:'pdb'},
        {abbr:'chemical/x-rosdal', name:'chemical/x-rosdal', ext:'ros'},
        {abbr:'chemical/x-swissprot', name:'chemical/x-swissprot', ext:'sw'},
        {abbr:'chemical/x-vamas-iso14976', name:'chemical/x-vamas-iso14976', ext:'vms'},
        {abbr:'chemical/x-vmd', name:'chemical/x-vmd', ext:'vmd'},
        {abbr:'chemical/x-xtel', name:'chemical/x-xtel', ext:'xtel'},
        {abbr:'chemical/x-xyz', name:'chemical/x-xyz', ext:'xyz'},
        {abbr:'image/cgm', name:'image/cgm'},
        {abbr:'image/g3fax', name:'image/g3fax'},
        {abbr:'image/gif', name:'image/gif', ext:'gif'},
        {abbr:'image/ief', name:'image/ief', ext:'ief'},
        {abbr:'image/jp2', name:'image/jp2', ext:'jp2'},
        {abbr:'image/jpeg', name:'image/jpeg', ext:'jpeg'},
        {abbr:'image/jpm', name:'image/jpm', ext:'jpm'},
        {abbr:'image/jpx', name:'image/jpx', ext:'jpx'},
        {abbr:'image/naplps', name:'image/naplps'},
        {abbr:'image/pcx', name:'image/pcx', ext:'pcx'},
        {abbr:'image/png', name:'image/png', ext:'png'},
        {abbr:'image/prs.btif', name:'image/prs.btif'},
        {abbr:'image/prs.pti', name:'image/prs.pti'},
        {abbr:'image/svg+xml', name:'image/svg+xml', ext:'svg'},
        {abbr:'image/tiff', name:'image/tiff', ext:'tiff'},
        {abbr:'image/vnd.cns.inf2', name:'image/vnd.cns.inf2'},
        {abbr:'image/vnd.djvu', name:'image/vnd.djvu', ext:'djvu'},
        {abbr:'image/vnd.dwg', name:'image/vnd.dwg'},
        {abbr:'image/vnd.dxf', name:'image/vnd.dxf'},
        {abbr:'image/vnd.fastbidsheet', name:'image/vnd.fastbidsheet'},
        {abbr:'image/vnd.fpx', name:'image/vnd.fpx'},
        {abbr:'image/vnd.fst', name:'image/vnd.fst'},
        {abbr:'image/vnd.fujixerox.edmics-mmr', name:'image/vnd.fujixerox.edmics-mmr'},
        {abbr:'image/vnd.fujixerox.edmics-rlc', name:'image/vnd.fujixerox.edmics-rlc'},
        {abbr:'image/vnd.microsoft.icon', name:'image/vnd.microsoft.icon', ext:'ico'},
        {abbr:'image/vnd.mix', name:'image/vnd.mix'},
        {abbr:'image/vnd.net-fpx', name:'image/vnd.net-fpx'},
        {abbr:'image/vnd.svf', name:'image/vnd.svf'},
        {abbr:'image/vnd.wap.wbmp', name:'image/vnd.wap.wbmp', ext:'wbmp'},
        {abbr:'image/vnd.xiff', name:'image/vnd.xiff'},
        {abbr:'image/x-canon-cr2', name:'image/x-canon-cr2', ext:'cr2'},
        {abbr:'image/x-canon-crw', name:'image/x-canon-crw', ext:'crw'},
        {abbr:'image/x-cmu-raster', name:'image/x-cmu-raster', ext:'ras'},
        {abbr:'image/x-coreldraw', name:'image/x-coreldraw', ext:'cdr'},
        {abbr:'image/x-coreldrawpattern', name:'image/x-coreldrawpattern', ext:'pat'},
        {abbr:'image/x-coreldrawtemplate', name:'image/x-coreldrawtemplate', ext:'cdt'},
        {abbr:'image/x-corelphotopaint', name:'image/x-corelphotopaint', ext:'cpt'},
        {abbr:'image/x-epson-erf', name:'image/x-epson-erf', ext:'erf'},
        {abbr:'image/x-icon', name:'image/x-icon'},
        {abbr:'image/x-jg', name:'image/x-jg', ext:'art'},
        {abbr:'image/x-jng', name:'image/x-jng', ext:'jng'},
        {abbr:'image/x-ms-bmp', name:'image/x-ms-bmp', ext:'bmp'},
        {abbr:'image/x-nikon-nef', name:'image/x-nikon-nef', ext:'nef'},
        {abbr:'image/x-olympus-orf', name:'image/x-olympus-orf', ext:'orf'},
        {abbr:'image/x-photoshop', name:'image/x-photoshop', ext:'psd'},
        {abbr:'image/x-portable-anymap', name:'image/x-portable-anymap', ext:'pnm'},
        {abbr:'image/x-portable-bitmap', name:'image/x-portable-bitmap', ext:'pbm'},
        {abbr:'image/x-portable-graymap', name:'image/x-portable-graymap', ext:'pgm'},
        {abbr:'image/x-portable-pixmap', name:'image/x-portable-pixmap', ext:'ppm'},
        {abbr:'image/x-rgb', name:'image/x-rgb', ext:'rgb'},
        {abbr:'image/x-xbitmap', name:'image/x-xbitmap', ext:'xbm'},
        {abbr:'image/x-xpixmap', name:'image/x-xpixmap', ext:'xpm'},
        {abbr:'image/x-xwindowdump', name:'image/x-xwindowdump', ext:'xwd'},
        {abbr:'inode/chardevice', name:'inode/chardevice'},
        {abbr:'inode/blockdevice', name:'inode/blockdevice'},
        {abbr:'inode/directory-locked', name:'inode/directory-locked'},
        {abbr:'inode/directory', name:'inode/directory'},
        {abbr:'inode/fifo', name:'inode/fifo'},
        {abbr:'inode/socket', name:'inode/socket'},
        {abbr:'message/delivery-status', name:'message/delivery-status'},
        {abbr:'message/disposition-notification', name:'message/disposition-notification'},
        {abbr:'message/external-body', name:'message/external-body'},
        {abbr:'message/http', name:'message/http'},
        {abbr:'message/s-http', name:'message/s-http'},
        {abbr:'message/news', name:'message/news'},
        {abbr:'message/partial', name:'message/partial'},
        {abbr:'message/rfc822', name:'message/rfc822', ext:'eml'},
        {abbr:'model/iges', name:'model/iges', ext:'igs'},
        {abbr:'model/mesh', name:'model/mesh', ext:'msh'},
        {abbr:'model/vnd.dwf', name:'model/vnd.dwf'},
        {abbr:'model/vnd.flatland.3dml', name:'model/vnd.flatland.3dml'},
        {abbr:'model/vnd.gdl', name:'model/vnd.gdl'},
        {abbr:'model/vnd.gs-gdl', name:'model/vnd.gs-gdl'},
        {abbr:'model/vnd.gtw', name:'model/vnd.gtw'},
        {abbr:'model/vnd.mts', name:'model/vnd.mts'},
        {abbr:'model/vnd.vtu', name:'model/vnd.vtu'},
        {abbr:'model/vrml', name:'model/vrml', ext:'wrl'},
        {abbr:'model/x3d+vrml', name:'model/x3d+vrml', ext:'x3dv'},
        {abbr:'model/x3d+xml', name:'model/x3d+xml', ext:'x3d'},
        {abbr:'model/x3d+binary', name:'model/x3d+binary', ext:'x3db'},
        {abbr:'multipart/alternative', name:'multipart/alternative'},
        {abbr:'multipart/appledouble', name:'multipart/appledouble'},
        {abbr:'multipart/byteranges', name:'multipart/byteranges'},
        {abbr:'multipart/digest', name:'multipart/digest'},
        {abbr:'multipart/encrypted', name:'multipart/encrypted'},
        {abbr:'multipart/form-data', name:'multipart/form-data'},
        {abbr:'multipart/header-set', name:'multipart/header-set'},
        {abbr:'multipart/mixed', name:'multipart/mixed'},
        {abbr:'multipart/parallel', name:'multipart/parallel'},
        {abbr:'multipart/related', name:'multipart/related'},
        {abbr:'multipart/report', name:'multipart/report'},
        {abbr:'multipart/signed', name:'multipart/signed'},
        {abbr:'multipart/voice-message', name:'multipart/voice-message'},
        {abbr:'text/cache-manifest', name:'text/cache-manifest', ext:'appcache'},
        {abbr:'text/calendar', name:'text/calendar', ext:'ics'},
        {abbr:'text/css', name:'text/css', ext:'css'},
        {abbr:'text/csv', name:'text/csv', ext:'csv'},
        {abbr:'text/directory', name:'text/directory'},
        {abbr:'text/english', name:'text/english'},
        {abbr:'text/enriched', name:'text/enriched'},
        {abbr:'text/h323', name:'text/h323', ext:'323'},
        {abbr:'text/html', name:'text/html', ext:'html'},
        {abbr:'text/iuls', name:'text/iuls', ext:'uls'},
        {abbr:'text/mathml', name:'text/mathml', ext:'mml'},
        {abbr:'text/parityfec', name:'text/parityfec'},
        {abbr:'text/plain', name:'text/plain', ext:'asc'},
        {abbr:'text/prs.lines.tag', name:'text/prs.lines.tag'},
        {abbr:'text/rfc822-headers', name:'text/rfc822-headers'},
        {abbr:'text/richtext', name:'text/richtext', ext:'rtx'},
        {abbr:'text/rtf', name:'text/rtf'},
        {abbr:'text/scriptlet', name:'text/scriptlet', ext:'sct'},
        {abbr:'text/t140', name:'text/t140'},
        {abbr:'text/texmacs', name:'text/texmacs', ext:'tm'},
        {abbr:'text/tab-separated-values', name:'text/tab-separated-values', ext:'tsv'},
        {abbr:'text/turtle', name:'text/turtle', ext:'ttl'},
        {abbr:'text/uri-list', name:'text/uri-list'},
        {abbr:'text/vcard', name:'text/vcard', ext:'vcf'},
        {abbr:'text/vnd.abc', name:'text/vnd.abc'},
        {abbr:'text/vnd.curl', name:'text/vnd.curl'},
        {abbr:'text/vnd.debian.copyright', name:'text/vnd.debian.copyright'},
        {abbr:'text/vnd.DMClientScript', name:'text/vnd.DMClientScript'},
        {abbr:'text/vnd.flatland.3dml', name:'text/vnd.flatland.3dml'},
        {abbr:'text/vnd.fly', name:'text/vnd.fly'},
        {abbr:'text/vnd.fmi.flexstor', name:'text/vnd.fmi.flexstor'},
        {abbr:'text/vnd.in3d.3dml', name:'text/vnd.in3d.3dml'},
        {abbr:'text/vnd.in3d.spot', name:'text/vnd.in3d.spot'},
        {abbr:'text/vnd.IPTC.NewsML', name:'text/vnd.IPTC.NewsML'},
        {abbr:'text/vnd.IPTC.NITF', name:'text/vnd.IPTC.NITF'},
        {abbr:'text/vnd.latex-z', name:'text/vnd.latex-z'},
        {abbr:'text/vnd.motorola.reflex', name:'text/vnd.motorola.reflex'},
        {abbr:'text/vnd.ms-mediapackage', name:'text/vnd.ms-mediapackage'},
        {abbr:'text/vnd.sun.j2me.app-descriptor', name:'text/vnd.sun.j2me.app-descriptor', ext:'jad'},
        {abbr:'text/vnd.wap.si', name:'text/vnd.wap.si'},
        {abbr:'text/vnd.wap.sl', name:'text/vnd.wap.sl'},
        {abbr:'text/vnd.wap.wml', name:'text/vnd.wap.wml', ext:'wml'},
        {abbr:'text/vnd.wap.wmlscript', name:'text/vnd.wap.wmlscript', ext:'wmls'},
        {abbr:'text/x-bibtex', name:'text/x-bibtex', ext:'bib'},
        {abbr:'text/x-boo', name:'text/x-boo', ext:'boo'},
        {abbr:'text/x-c++hdr', name:'text/x-c++hdr', ext:'h++'},
        {abbr:'text/x-c++src', name:'text/x-c++src', ext:'c++'},
        {abbr:'text/x-chdr', name:'text/x-chdr', ext:'h'},
        {abbr:'text/x-component', name:'text/x-component', ext:'htc'},
        {abbr:'text/x-crontab', name:'text/x-crontab'},
        {abbr:'text/x-csh', name:'text/x-csh', ext:'csh'},
        {abbr:'text/x-csrc', name:'text/x-csrc', ext:'c'},
        {abbr:'text/x-dsrc', name:'text/x-dsrc', ext:'d'},
        {abbr:'text/x-diff', name:'text/x-diff', ext:'diff'},
        {abbr:'text/x-haskell', name:'text/x-haskell', ext:'hs'},
        {abbr:'text/x-java', name:'text/x-java', ext:'java'},
        {abbr:'text/x-lilypond', name:'text/x-lilypond', ext:'ly'},
        {abbr:'text/x-literate-haskell', name:'text/x-literate-haskell', ext:'lhs'},
        {abbr:'text/x-makefile', name:'text/x-makefile'},
        {abbr:'text/x-moc', name:'text/x-moc', ext:'moc'},
        {abbr:'text/x-pascal', name:'text/x-pascal', ext:'p'},
        {abbr:'text/x-pcs-gcd', name:'text/x-pcs-gcd', ext:'gcd'},
        {abbr:'text/x-perl', name:'text/x-perl', ext:'pl'},
        {abbr:'text/x-python', name:'text/x-python', ext:'py'},
        {abbr:'text/x-scala', name:'text/x-scala', ext:'scala'},
        {abbr:'text/x-server-parsed-html', name:'text/x-server-parsed-html'},
        {abbr:'text/x-setext', name:'text/x-setext', ext:'etx'},
        {abbr:'text/x-sfv', name:'text/x-sfv', ext:'sfv'},
        {abbr:'text/x-sh', name:'text/x-sh', ext:'sh'},
        {abbr:'text/x-tcl', name:'text/x-tcl', ext:'tcl'},
        {abbr:'text/x-tex', name:'text/x-tex', ext:'tex'},
        {abbr:'text/x-vcalendar', name:'text/x-vcalendar', ext:'vcs'},
        {abbr:'video/3gpp', name:'video/3gpp', ext:'3gp'},
        {abbr:'video/annodex', name:'video/annodex', ext:'axv'},
        {abbr:'video/dl', name:'video/dl', ext:'dl'},
        {abbr:'video/dv', name:'video/dv', ext:'dif'},
        {abbr:'video/fli', name:'video/fli', ext:'fli'},
        {abbr:'video/gl', name:'video/gl', ext:'gl'},
        {abbr:'video/mpeg', name:'video/mpeg', ext:'mpeg'},
        {abbr:'video/MP2T', name:'video/MP2T', ext:'ts'},
        {abbr:'video/mp4', name:'video/mp4', ext:'mp4'},
        {abbr:'video/quicktime', name:'video/quicktime', ext:'qt'},
        {abbr:'video/mp4v-es', name:'video/mp4v-es'},
        {abbr:'video/ogg', name:'video/ogg', ext:'ogv'},
        {abbr:'video/parityfec', name:'video/parityfec'},
        {abbr:'video/pointer', name:'video/pointer'},
        {abbr:'video/webm', name:'video/webm', ext:'webm'},
        {abbr:'video/vnd.fvt', name:'video/vnd.fvt'},
        {abbr:'video/vnd.motorola.video', name:'video/vnd.motorola.video'},
        {abbr:'video/vnd.motorola.videop', name:'video/vnd.motorola.videop'},
        {abbr:'video/vnd.mpegurl', name:'video/vnd.mpegurl', ext:'mxu'},
        {abbr:'video/vnd.mts', name:'video/vnd.mts'},
        {abbr:'video/vnd.nokia.interleaved-multimedia', name:'video/vnd.nokia.interleaved-multimedia'},
        {abbr:'video/vnd.vivo', name:'video/vnd.vivo'},
        {abbr:'video/x-flv', name:'video/x-flv', ext:'flv'},
        {abbr:'video/x-la-asf', name:'video/x-la-asf', ext:'lsf'},
        {abbr:'video/x-mng', name:'video/x-mng', ext:'mng'},
        {abbr:'video/x-ms-asf', name:'video/x-ms-asf', ext:'asf'},
        {abbr:'video/x-ms-wm', name:'video/x-ms-wm', ext:'wm'},
        {abbr:'video/x-ms-wmv', name:'video/x-ms-wmv', ext:'wmv'},
        {abbr:'video/x-ms-wmx', name:'video/x-ms-wmx', ext:'wmx'},
        {abbr:'video/x-ms-wvx', name:'video/x-ms-wvx', ext:'wvx'},
        {abbr:'video/x-msvideo', name:'video/x-msvideo', ext:'avi'},
        {abbr:'video/x-sgi-movie', name:'video/x-sgi-movie', ext:'movie'},
        {abbr:'video/x-matroska', name:'video/x-matroska', ext:'mpv'},
        {abbr:'x-conference/x-cooltalk', name:'x-conference/x-cooltalk', ext:'ice'},
        {abbr:'x-epoc/x-sisx-app', name:'x-epoc/x-sisx-app', ext:'sisx'},
        {abbr:'x-world/x-vrml', name:'x-world/x-vrml', ext:'vrm'}

]});			

